/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import expedientes.Administrador;
import javax.swing.JOptionPane;

/**
 *
 * @author N04117
 */
public class Bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    public boolean creoVentana;
    public Inicio ventanaIni;
    
    public Bienvenido() {
        initComponents();
        creoVentana = false;
    }
    
    public Bienvenido(Inicio c) {
        initComponents();
        ventanaIni = c;
        creoVentana = false;
    }
    
    public void SetCreoVentana(boolean b){
        creoVentana = b;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JToggleButton();
        btnRegNewExp = new javax.swing.JToggleButton();
        btnVerMovExp = new javax.swing.JToggleButton();
        btnFinRegExp = new javax.swing.JToggleButton();
        btnInfInteresado = new javax.swing.JToggleButton();
        btnCrearDep = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRegNewExp.setText("Registrar nuevo expediente");
        btnRegNewExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegNewExpActionPerformed(evt);
            }
        });

        btnVerMovExp.setText("Ver movimiento de expediente");
        btnVerMovExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMovExpActionPerformed(evt);
            }
        });

        btnFinRegExp.setText("Finalizar registro de expediente");
        btnFinRegExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinRegExpActionPerformed(evt);
            }
        });

        btnInfInteresado.setText("Informar al interesado");
        btnInfInteresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfInteresadoActionPerformed(evt);
            }
        });

        btnCrearDep.setText("Crear dependencia");
        btnCrearDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearDep)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFinRegExp)
                        .addGap(43, 43, 43)
                        .addComponent(btnInfInteresado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegNewExp)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerMovExp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegNewExp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerMovExp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfInteresado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearDep, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //Salida
        if (creoVentana){
            Administrador.AdvertirError("Hay una venta abierta", "");
        }
        else{
            ventanaIni.ventanaWelcome = null;
            this.dispose();
        }
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRegNewExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNewExpActionPerformed
        if (!creoVentana){
            IngresoExp ventanaIngExp = new IngresoExp(this);
            ventanaIngExp.setVisible(true);
            creoVentana = true;
        }
    }//GEN-LAST:event_btnRegNewExpActionPerformed

    private void btnVerMovExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMovExpActionPerformed
        if (!creoVentana){
            VerMovimientos ventanaMovimientos = new VerMovimientos(this);
            ventanaMovimientos.setVisible(true);
            creoVentana = true;
        }
    }//GEN-LAST:event_btnVerMovExpActionPerformed

    private void btnFinRegExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinRegExpActionPerformed
        if (!creoVentana){
            FinalizarVentana ventanaFinExp = new FinalizarVentana(this);
            ventanaFinExp.setVisible(true);
            creoVentana = true;
        }
    }//GEN-LAST:event_btnFinRegExpActionPerformed

    private void btnInfInteresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfInteresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfInteresadoActionPerformed

    private void btnCrearDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDepActionPerformed
        // TODO add your handling code here:
        if (!creoVentana){
            IngresoDependencia ventanaCrearDep = new IngresoDependencia(this);
            ventanaCrearDep.setVisible(true);
            creoVentana = true;
        }
    }//GEN-LAST:event_btnCrearDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCrearDep;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JToggleButton btnFinRegExp;
    private javax.swing.JToggleButton btnInfInteresado;
    private javax.swing.JToggleButton btnRegNewExp;
    private javax.swing.JToggleButton btnVerMovExp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
