/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import expedientes.Administrador;
import expedientes.Movimiento;
import expedientes.Tramite;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import tda.Pila;

/**
 *
 * @author N04117
 */
public class VerMovimientos extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private Bienvenido home;
    private boolean creoVentana;
    private Tramite encontrado;
    private int posicion;
    
    public VerMovimientos() {
        initComponents();
    }
    
    public VerMovimientos(Bienvenido home) {
        initComponents();
        this.home = home;
        this.creoVentana = false;
        this.encontrado = null;
        this.posicion = 1;
        btnAgregar.setEnabled(false);
        
        btnMovIzq.setEnabled(false);
        btnMovDer.setEnabled(false);
    }
    
    public void SetCreoVentana(boolean b){
        creoVentana = b;
    }
    
    private void ActualizarEstado(){
        if (!encontrado.esFinalizado()){
            lbEstado.setText("Estado:\nActivo");
            btnAgregar.setEnabled(true);
        }
        else{
            lbEstado.setText("Estado:\nFinalizado");
            btnAgregar.setEnabled(false);
        }
    }
    
    private void ActualizarFlechas(){
        int total = Administrador.listaTramitesTotales.longitud();
        if (Administrador.listaTramitesTotales.esVacia()){
            btnMovIzq.setEnabled(false);
            btnMovDer.setEnabled(false);
            return;
        }
        
        if (posicion == 1) btnMovIzq.setEnabled(false);
        else btnMovIzq.setEnabled(true);

        if (posicion == total) btnMovDer.setEnabled(false);
        else btnMovDer.setEnabled(true);
    }
    
    public void ActualizarTabla(){
        //Crear la tabla
        DefaultTableModel modelTable = new DefaultTableModel(new Object[]{"Fecha Entrada","Fecha Salida","Lugar","Encargado"},0);
        tableMoves.setModel(modelTable);
        
        //Rellenarla
        Administrador.admMov.setTramiteReg(encontrado);
        Administrador.admMov.CrearTablaDeMovimientos(modelTable);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JToggleButton();
        tfID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMoves = new javax.swing.JTable();
        lbEstado = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnMovIzq = new javax.swing.JButton();
        btnMovDer = new javax.swing.JButton();
        chbBuscar = new javax.swing.JCheckBox();

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("ID");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("/");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ver Movimiento");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("ID");

        btnExit.setText("Atras");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tfID.setText("abc123");
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tableMoves.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tableMoves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Entrada", "Fecha Salida", "Nombre", "Encargado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableMoves);
        if (tableMoves.getColumnModel().getColumnCount() > 0) {
            tableMoves.getColumnModel().getColumn(0).setMinWidth(100);
            tableMoves.getColumnModel().getColumn(1).setMinWidth(100);
        }

        lbEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstado.setText("Estado:");
        lbEstado.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnMovIzq.setText("<-");
        btnMovIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovIzqActionPerformed(evt);
            }
        });

        btnMovDer.setText("->");
        btnMovDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovDerActionPerformed(evt);
            }
        });

        chbBuscar.setSelected(true);
        chbBuscar.setText("Buscar/Seguir");
        chbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnMovIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMovDer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMovDer)
                            .addComponent(btnMovIzq))
                        .addGap(16, 16, 16)
                        .addComponent(chbBuscar)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //Salida
        if (creoVentana){
            Administrador.AdvertirError("Hay una venta abierta", "");
        }
        else{
            home.SetCreoVentana(false);
            this.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
       
    }//GEN-LAST:event_tfIDActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (creoVentana){
            Administrador.AdvertirError("Hay una venta abierta", "");
            return;
        }
        //Obtener el tramite
        String id = tfID.getText();
        int posIDT = Administrador.ExisteTramite(id);
        if (posIDT == -1){
            Administrador.AdvertirError("No existe tramite con ese ID", "");
            return;
        }
        encontrado = Administrador.listaTramitesTotales.iesimo(posIDT);
        //Sacarlo de los tramites activos o finalizados
        ActualizarEstado();
        //Hacer las filas de la tala
        ActualizarTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!creoVentana){
            IngresoMovimiento ventanaMov = new IngresoMovimiento(this, encontrado);
            ventanaMov.setVisible(true);
            creoVentana = true;
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void chbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbBuscarActionPerformed
        boolean esModoBuscar = (chbBuscar.isSelected());
        if (creoVentana){
            Administrador.AdvertirError("Hay una venta abierta", "");
            chbBuscar.setSelected(!esModoBuscar);
            return;
        }
        btnMovIzq.setEnabled(!esModoBuscar);
        btnMovDer.setEnabled(!esModoBuscar);

        tfID.setEnabled(esModoBuscar);
        btnBuscar.setEnabled(esModoBuscar);
        
        if (!esModoBuscar) {
            encontrado = Administrador.listaTramitesTotales.iesimo(posicion);
            if (encontrado != null){
                //Sacarlo de los tramites activos o finalizados
                ActualizarEstado();
                //Hacer las filas de la tala
                ActualizarTabla();
            }
            ActualizarFlechas();
            tfID.setText(encontrado.getId());
        }
    }//GEN-LAST:event_chbBuscarActionPerformed

    private void btnMovIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovIzqActionPerformed
        if (creoVentana){
            Administrador.AdvertirError("Hay una venta abierta", "");
            return;
        }
        posicion--;
        //Obtener el tramite
        encontrado = Administrador.listaTramitesTotales.iesimo(posicion);
        //Sacarlo de los tramites activos o finalizados
        ActualizarEstado();
        //Hacer las filas de la tala
        ActualizarTabla();
        
        //Actualizar La Flecha
        ActualizarFlechas();
        tfID.setText(encontrado.getId());
    }//GEN-LAST:event_btnMovIzqActionPerformed

    private void btnMovDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovDerActionPerformed
        if (creoVentana){
            Administrador.AdvertirError("Hay una venta abierta", "");
            return;
        }
        posicion++;
        //Obtener el tramite
        encontrado = Administrador.listaTramitesTotales.iesimo(posicion);
        //Sacarlo de los tramites activos o finalizados
        ActualizarEstado();
        //Hacer las filas de la tala
        ActualizarTabla();
        
        //Actualizar La Flecha
        ActualizarFlechas();
        tfID.setText(encontrado.getId());
    }//GEN-LAST:event_btnMovDerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerMovimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JButton btnMovDer;
    private javax.swing.JButton btnMovIzq;
    private javax.swing.JCheckBox chbBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JTable tableMoves;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables
}
